package com.myspace.events_sample;

/**
 * This class was automatically generated by the data modeler tool.
 */
import org.kie.api.remote.Remotable;

@Remotable
public class IncomingRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String description;
	private java.lang.String priority;

	public IncomingRequest() {
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;

	}

	public java.lang.String getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.String priority) {
		this.priority = priority;
	}

	public IncomingRequest(java.lang.String description,
			java.lang.String priority) {
		this.description = description;
		this.priority = priority;
	}

}